<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150809110131 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE neosmeetuphh_todolist_domain_model_item (persistence_object_identifier VARCHAR(40) NOT NULL, list VARCHAR(40) DEFAULT NULL, `label` VARCHAR(255) NOT NULL, done TINYINT(1) NOT NULL, createdat DATETIME NOT NULL, INDEX IDX_204B19E044C8F818 (list), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE neosmeetuphh_todolist_domain_model_todolist (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE neosmeetuphh_todolist_domain_model_item ADD CONSTRAINT FK_204B19E044C8F818 FOREIGN KEY (list) REFERENCES neosmeetuphh_todolist_domain_model_todolist (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE neosmeetuphh_todolist_domain_model_item DROP FOREIGN KEY FK_204B19E044C8F818");
		$this->addSql("DROP TABLE neosmeetuphh_todolist_domain_model_item");
		$this->addSql("DROP TABLE neosmeetuphh_todolist_domain_model_todolist");
	}
}